AGNTProcessor:
  ModuleDir: /home/ns3/py_charm_workspace/paper_subastas/auction/proc_modules
  ModuleDynamicLoad: true
  Modules: basic_module
Control:
  Access:
    Host: All
    User: admin:admin
  ControlPort: 12248
  LogCommand: true
  LogOnConnect: true
  UseSSL: false
DataBase:
  DbName: auction_client_db
  Host: localhost
  MaxSize: 5
  MinSize: 1
  Password: postgres
  Port: 5432
  Type: postgres
  User: postgres
DefaultLogFile: netagent
Main:
  AuctionfileDtd: auctionfile.dtd
  BiddingObjectfileDtd: bidfile.dtd
  DefaultDestinationAddr-V4: 127.0.0.1
  DefaultDestinationAddr-V6: 0:0:0:0:0:0:0:0
  DefaultDestinationPort: 8080
  DefaultProtocol: 6
  DefaultSourcePort: 8020
  Domain: '16'
  ImmediateStart: true
  LifeTime: 60
  LocalAddr-V4: 127.0.0.1
  LocalAddr-V6: 0:0:0:0:0:0:0:0
  ResourceRequestFile: aggregate_basic.xml
  ResourceRequestFileDtd: resourcerequestfile.dtd
  StoreObjects: true
  TimeFormat: '%Y%m%d %H%M%S'
  TimeOut: 5
  UseIPv6: false
