AUMProcessor:
  ModuleDir: /home/ns3/py_charm_workspace/paper_subastas/auction/proc_modules
  ModuleDynamicLoad: true
  Modules: basic_module
  basic_module:
    Burts:
      Name: Rate
      Type: UInt32
      Value: 1556
    NextId:
      Name: NextId
      Type: UInt32
      Value: 100
    Rate:
      Name: Rate
      Type: UInt32
      Value: 102400
Control:
  Access:
    Host: All
    User: admin:admin
  ControlPort: 12248
  LocalAddr-V6: 0:0:0:0:0:0:0:0
  LogCommand: true
  LogOnConnect: true
  UseSSL: false
DataBase:
  DbName: auction_server_db
  Host: localhost
  MaxSize: 5
  MinSize: 1
  Password: postgres
  Port: 5432
  Type: postgres
  User: postgres
DefaultLogFile: netaum
Main:
  AuctionFile: auction_psp.xml
  AuctionFileDtd: auctionfile.dtd
  BiddingObjectfileDtd: bidfile.dtd
  DefaultProtocol: 6
  Domain: '103'
  ImmediateStart: true
  LifeTime: 60
  LocalAddr-V4: 127.0.0.1
  LocalAddr-V6: 0:0:0:0:0:0:0:0
  LocalPort: 8080
  ResourceFile: resources.yaml
  StoreObjects: true
  TimeFormat: '%Y%m%d %H%M%S'
  UseIPv6: false
  VerboseLevel: 4
