# auction_agent.yaml
Postgres:
  Database: auctiondb
  User: auction_user
  Password: auction_pass
  Host: localhost
  Port: 5432
  Minsize: 1
  Maxsize: 5

Main:
  Domain: 10
  ResourceRequestFileDtd: resourcerequestfile.dtd
  ResourceRequestFile: example_resource_request1.xml
  UseIPv6: No
  LocalAddr-V4: 127.0.0.1
  LocalAddr-V6: 0:0:0:0:0:0:0:0
  DefaultDestinationAddr-V4: 127.0.0.1
  DefaultDestinationAddr-V6: 0:0:0:0:0:0:0:0
  DefaultDestinationPort: 8080
  DefaultSourcePort: 8020
  # Tcp by default.
  ImmediateStart: True
  DefaultProtocol: 6
  LifeTime: 60
  # Timeout for server connections
  TimeOut: 5
  TimeFormat: "%Y%m%d %H%M%S"
  AuctionfileDtd: auctionfile.dtd
  DtdRootNode: AUCTIONSET
  BidfileDtd: bidfile.dtd

Control:
  ControlPort: 12248
  UseSSL: No
  LogOnConnect: yes
  LogCommand: yes
  Access:
    Host: All
    User: admin:admin

AGNTProcessor:
  ModuleDir: /home/ns3/py_charm_workspace/paper_subastas/auction/proc_modules
  ModuleDynamicLoad: yes
  Modules: basic_module

DefaultLogFile: netagent

