# auction_server.yaml
Postgres:
  Database: auctiondb
  User: auction_user
  Password: auction_pass
  Host: localhost
  Port: 5432
  MinSize: 1
  MaxSize: 5

Main:
  VerboseLevel: 4
  Domain: 1
  UseIPv6: No
  LocalAddr-V4: 127.0.0.1
  LocalPort: 8080
  DefaultProtocol: 6
  LifeTime: 60
  TimeFormat: "%Y%m%d %H%M%S"
  ImmediateStart: True
  ResourceFile: resources.yaml
  AuctionFileDtd: auctionfile.dtd
  AuctionFile: example_auctions3.xml
  AuctionRootNode: AUCTIONSET
  BidfileDtd: bidfile.dtd


Control:
  ControlPort: 12248
  UseSSL: No
  LogOnConnect: yes
  LogCommand: yes
  LocalAddr-V6: 0:0:0:0:0:0:0:0
  Access:
    Host: All
    User: admin:admin

AUMProcessor:
  ModuleDir: /home/ns3/py_charm_workspace/paper_subastas/auction/proc_modules
  ModuleDynamicLoad: yes
  Modules: basic_module
  basic_module:
    Rate:
      Name: Rate
      Type: UInt32
      Value: 102400
    Burts:
      Name: Rate
      Type: UInt32
      Value: 1556
    NextId:
      Name: NextId
      Type: UInt32
      Value: 100

DefaultLogFile: netaum.log
