# auction_server.yaml
Postgres:
  Database: auctiondb
  User: auction_user
  Password: auction_pass
  Host: localhost
  Port: 5432
  MinSize: 1
  MaxSize: 5

Main:
  VerboseLevel: 4
  Domain: 1
  ResourceRequestFile: example_resource_request1.xml
  DefaultDestinAddr: 192.168.3.3
  DefaultDestinPort: 80
  DefaultProtocol: 6
  DefaultSourcePort: 12248
  TimeFormat: "%Y%m%d %H%M%S"
  ImmediateStart: True

Control:
  ControlPort: 12248
  UseSSL: No
  UseIPv6: No
  LogOnConnect: yes
  LogCommand: yes
  LocalAddr-V4: 192.168.2.11
  LocalAddr-V6: 0:0:0:0:0:0:0:0
  Access:
    Host: All
    User: admin:admin

AUMProcessor:
  ModuleDir: /home/ns3/py_charm_workspace/paper_subastas/auction/proc_modules
  ModuleDynamicLoad: yes
  Modules: basic_server_module
  basic_server_module:
    Rate:
      Name: Rate
      Type: UInt32
      Value: 102400
    Burts:
      Name: Rate
      Type: UInt32
      Value: 1556
    NextId:
      Name: NextId
      Type: UInt32
      Value: 100


ResourceFile: resources.yaml
AuctionFileDtd: auctionfile.dtd
AuctionFile: example_auctions3.xml
AuctionRootNode: AUCTIONSET
BidfileDtd: bidfile.dtd
DefaultLogFile: netaum.log
