# auction_agent.yaml
postgres:
  database: auctiondb
  user: auction_user
  password: auction_pass
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

Main:
  ResourceRequestFileDtd: resourcerequestfile.dtd
  ResourceRequestFile: example_resource_request1.xml
  UseIPv6: No
  LocalAddr-V4: 192.168.2.11
  LocalAddr-V6: 0:0:0:0:0:0:0:0
  DefaultDestinationAddr-V4: 192.168.3.3
  DefaultDestinationAddr-V6: 0:0:0:0:0:0:0:0
  DefaultDestinationPort: 80
  DefaultSourcePort: 12248
  # Tcp by default.
  DefaultProtocol: 6
  LifeTime: 60
  TimeFormat: "%Y%m%d %H%M%S"

Control:
  ControlPort: 12248
  UseSSL: No
  LogOnConnect: yes
  LogCommand: yes
  Access:
    Host: All
    User: admin:admin

AGNTProcessor:
  ModuleDir: /home/ns3/py_charm_workspace/paper_subastas/auction/proc_modules
  ModuleDynamicLoad: yes
  Modules: basic_client_module


AuctionfileDtd: auctionfile.dtd
DtdRootNode: AUCTIONSET
BidfileDtd: bidfile.dtd
DefaultLogFile: netaum.log

